#        -*- Dockerfile -*-
#
# Recipe to build a container image for dash-mpd-cli + helper applications, for Linux/riscv64
#
# This Containerfile contains the recipe needed to generate a docker/podman/OCI container image
# including the dash-mpd-cli binary alongside the external helper applications that it uses for
# muxing media streams, for extracting/converting subtitle streams, and for decrypting content
# infected with DRM. These are packaged with a minimal Alpine Linux installation (here the "edge"
# distribution, because there is not yet an official distribution for riscv64).
#
# To build the container locally (not needed for an end user)
#
#   podman manifest create dash-mpd-cli
#   podman build -f etc/Containerfile_linux_riscv64 --platform linux/riscv64 --tag dash-mpd-cli-linux-riscv64 --manifest dash-mpd-cli .


# We make a static build of MP4Box from GPAC, which is not packaged for Alpine Linux.
# https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux
#
# We aren't able to include shaka-packager for riscv64. It's not packed for Alpine Linux and not
# distributed in binary form for RISCV64. Attempts to build from source fail due to an error
# building the third party library abseil-cpp (missing declaration of off64_t).
FROM --platform=linux/riscv64 docker.io/alpine:edge AS builder
WORKDIR /src
COPY ./ ./
RUN apk update && \
    apk upgrade && \
    apk add --no-cache bash curl bsd-compat-headers linux-headers build-base file musl-dev pkgconfig git g++ binutils make cmake zlib-dev zlib-static ninja python3 cargo rust && \
    cd /src && cargo update && \
    cargo build --release && \
    git clone https://github.com/gpac/gpac.git && \
    cd gpac && ./configure --static-bin && \
    make -j 4 && \
    ls -l bin/gcc/ && \
    file bin/gcc/MP4Box

# Now build the final image
FROM --platform=linux/riscv64 docker.io/alpine:edge
LABEL org.opencontainers.image.description="Download media content from a DASH-MPEG or DASH-WebM MPD manifest." \
    org.opencontainers.image.title="dash-mpd-cli" \
    org.opencontainers.image.url="https://github.com/emarsden/dash-mpd-cli" \
    org.opencontainers.image.source="https://github.com/emarsden/dash-mpd-cli" \
    org.opencontainers.image.version="0.2.11" \
    org.opencontainers.image.authors="eric.marsden@risk-engineering.org" \
    org.opencontainers.image.licenses="MIT,GPL-2.0-or-later"

# Install our external dependencies. Licences for the external dependencies:
#   - ffmpeg: GNU GPL v2
#   - mkvmerge (from mkvtoolnix): GNU GPL v2 -- not packaged in this container
#   - vlc: GNU GPL v2, not installed because it inflates image size considerably
#   - mp4decrypt (from bento4): GNU GPL v2
#   - xsltproc (from libxslt): MIT
#   - Shaka packager: MIT -- not packaged in this container
#
# Note that as of 2023-12, mkvtoolnix is not packaged in alpine:edge/riscv64.
RUN apk update && \
    apk upgrade && \
    apk add --no-cache ca-certificates libc6-compat wget ffmpeg bento4 libxslt && \
    update-ca-certificates && \
    mkdir /content && \
    chown root.root /content && \
    chmod a=rwx,o+t /content

COPY --from=builder --chown=root:root --chmod=755 \
    /src/target/release/dash-mpd-cli /usr/local/bin
COPY --from=builder --chown=root:root --chmod=755 \
    /src/gpac/bin/gcc/MP4Box /usr/local/bin

WORKDIR /content
ENTRYPOINT ["/usr/local/bin/dash-mpd-cli"]

# Size of our container image:
#   with vlc:     331 MB
#   without vlc nor mkvtoolnix: 133 MB  (riscv64)
