[book]
title = "Using dash-mpd-cli"
authors = ["Eric Marsden <eric.marsden@risk-engineering.org>"]
description = "User manual for the dash-mpd-cli commandline application."
language = "en"
src = "src"


[output.html]
git-repository-url = "https://github.com/emarsden/dash-mpd-cli"
git-repository-icon = "fab-github"
smart-punctuation = true
admonitions = true
