# Test the build for MacOS universal binaries
#

on: workflow_dispatch

name: Build MacOS universal binary

# This is currently needed to build the http3 functionality in the reqwest crate
env:
  RUSTFLAGS: '--cfg reqwest_unstable'

jobs:
  build-universal:
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v7.0.1
      with:
        fetch-depth: 0

    - uses: mlugg/setup-zig@v2

    - run: |
        brew install rustup
        export PATH="/opt/homebrew/opt/rustup/bin:$PATH"
        rustup install stable-aarch64-apple-darwin
        rustup target add x86_64-apple-darwin
        cargo install --locked cargo-zigbuild
        cargo zigbuild --release --target universal2-apple-darwin




#         podman pull docker.io/messense/cargo-zigbuild
#         podman run --rm \
#           -v ${GITHUB_WORKSPACE}:/io \
#           -w /io docker.io/messense/cargo-zigbuild \
#           brew install cmake && \
#           cargo zigbuild --release --target universal2-apple-darwin


